In [2]:
import pandas as pd

In [3]:
from sqlalchemy import create_engine

In [4]:
import csv

In [11]:
df = pd.read_csv('data-2263-2025-08-25.csv', sep=';', skiprows=1)

In [6]:
# Настройка отображения всех столбцов
pd.set_option('display.max_columns', None)

In [12]:
df.head()

,global_id,Тип образовательной организации,Статус организации,КПП,Лицензирование и аккредитация,ОГРН,Организационно-правовая форма,Подчинение,ФИО руководителя,Юридический адрес,Контактный телефон,Адрес электронной почты,Сайт,Образовательные программы,Образовательные услуги,Количество обучающихся по ОО,Контингент обучающихся дошкольников по ОО,Код ЕКИС,Полное наименование,Сокращённое наименование,Номер,Адреса учреждения,ИНН,Кружки и секции,geoData,geodata_center,Unnamed: 26
0,2707620431,профессиональная образовательная организация,действующее,771601001,nested data,1057716005676,бюджетное,Городское подчинение ДОНМ,Лунькин Александр Николаевич,"129337, г. Москва, Хибинский проезд, д.10",nested data,nested data,kst.mskobr.ru,Профессиональное обучение # Профессиональное о...,nested data,nested data,nested data,11688,Государственное бюджетное профессиональное обр...,ГБПОУ КСТ,NaN,nested data,7716237691,nested data,"{coordinates=[[[[37.67924019, 55.855094362], [...","{coordinates=[37.680189359, 55.856497466], typ...",NaN
1,2707621917,профессиональная образовательная организация,действующее,772101001,nested data,1037739525031,бюджетное,Городское подчинение ДОНМ,Курачёва Ирина Михайловна,"109457, г. Москва, ул. Федора Полетаева, д. 2,...",nested data,nested data,mpk.mskobr.ru,Профессиональное обучение # Профессиональное о...,nested data,nested data,nested data,14554,Государственное бюджетное профессиональное обр...,"ГБПОУ «Московский педагогический колледж» , ГБ...",NaN,nested data,7721222323,nested data,"{coordinates=[[[[37.773467204, 55.714584323], ...","{coordinates=[37.774186046, 55.71463069], type...",NaN
2,2707621993,профессиональная образовательная организация,действующее,774301001,nested data,1057743026461,бюджетное,Городское подчинение ДОНМ,Сидоренко Николай Андреевич,"125080, г. Москва, Светлый проезд, дом 2а",nested data,nested data,college57.mskobr.ru,Профессиональное обучение # Профессиональное о...,nested data,nested data,nested data,13443,Государственное бюджетное профессиональное обр...,ГБПОУ ТПСК им. В.М. Максимчука,NaN,nested data,7743085744,nested data,"{coordinates=[[[[37.631574066, 55.680368484], ...","{coordinates=[37.608620707, 55.679963725], typ...",NaN
3,2720796316,профессиональная образовательная организация,действующее,772401001,nested data,1037739222070,бюджетное,Городское подчинение ДОНМ,Седова Наталья Николаевна,"115569, г. Москва, Шипиловский проезд, дом 37,...",nested data,nested data,collegetsaritsyno.mskobr.ru,Профессиональное образование | среднее професс...,nested data,nested data,nested data,11708,Государственное бюджетное профессиональное обр...,ГБПОУ колледж «Царицыно»,NaN,nested data,7737057354,nested data,"{coordinates=[[[[37.695848768, 55.61318208], [...","{coordinates=[37.715097715, 55.623445754], typ...",NaN
4,2720796369,профессиональная образовательная организация,действующее,770501001,nested data,1057705003619,бюджетное,Городское подчинение ДОНМ,Павлюк Иван Андреевич,"115172, г. Москва, ул. Большие Каменщики, дом 7",nested data,nested data,ks54.mskobr.ru,Профессиональное обучение # Профессиональное о...,nested data,nested data,nested data,12974,Государственное бюджетное профессиональное обр...,ГБПОУ КС № 54,54.0,nested data,7705513734,nested data,"{coordinates=[[[[37.654537261, 55.739269548], ...","{coordinates=[37.626412255, 55.891675573], typ...",NaN

In [8]:
db_connection_str = 'postgresql+psycopg2://postgres:postgres@localhost:5432/schooldata'
engine = create_engine(db_connection_str)

In [13]:
df.to_sql('schools', engine, if_exists='replace', index=False)

572

In [9]:
df[['global_id', 'OrgType', 'LegalOrganization', 'LegalAddress', 'ShortName', 'geodata_center']].head()

,global_id,OrgType,LegalOrganization,LegalAddress,ShortName,geodata_center
0,global_id,Тип образовательной организации,Организационно-правовая форма,Юридический адрес,Сокращённое наименование,geodata_center
1,2707620431,профессиональная образовательная организация,бюджетное,"129337, г. Москва, Хибинский проезд, д.10",ГБПОУ КСТ,"{coordinates=[37.680189359, 55.856497466], typ..."
2,2707621917,профессиональная образовательная организация,бюджетное,"109457, г. Москва, ул. Федора Полетаева, д. 2,...","ГБПОУ «Московский педагогический колледж» , ГБ...","{coordinates=[37.774186046, 55.71463069], type..."
3,2707621993,профессиональная образовательная организация,бюджетное,"125080, г. Москва, Светлый проезд, дом 2а",ГБПОУ ТПСК им. В.М. Максимчука,"{coordinates=[37.608620707, 55.679963725], typ..."
4,2720796316,профессиональная образовательная организация,бюджетное,"115569, г. Москва, Шипиловский проезд, дом 37,...",ГБПОУ колледж «Царицыно»,"{coordinates=[37.715097715, 55.623445754], typ..."

In [7]:
df.iloc[2]['geodata_center']

'{coordinates=[[[[37.687809497, 55.778008355], [37.688003212, 55.778102216], [37.688064307, 55.77806199], [37.688225339, 55.778143743], [37.68822971, 55.778203619], [37.688286334, 55.778232112], [37.688286334, 55.778278204], [37.688381702, 55.778324296], [37.688682705, 55.778134061], [37.688684195, 55.778078751], [37.688556045, 55.778016736], [37.688518793, 55.778037687], [37.688041955, 55.777801358], [37.687816948, 55.777944664], [37.687809497, 55.778008355]]], [[[37.711001873, 55.762921204], [37.71116066, 55.762860842], [37.711166382, 55.762804503], [37.711119175, 55.762771505], [37.711335182, 55.762686192], [37.711426735, 55.762759433], [37.711582661, 55.762698265], [37.711584091, 55.762639512], [37.711366654, 55.762460837], [37.710780144, 55.762687802], [37.710783005, 55.762742531], [37.711001873, 55.762921204]]]], type=MultiPolygon}'

In [8]:
df.iloc[2]['geodata_center']

'{coordinates=[37.688373846, 55.77807037], type=Point}'

In [5]:
df[df['FullName'].str.contains('еникс')]['FullName'].head()

155    Государственное бюджетное общеобразовательное ...
Name: FullName, dtype: object

In [12]:
df[df['FullName'].str.contains('еникс')]['FullName'].tolist()

['Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 1798 «Феникс»']

In [7]:
import ast

In [14]:
with open('data-2263-2025-08-25.csv', newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile, delimiter=';')
        next(reader)
        for row in reader:
            
            coordinates_str = row['geodata_center']
            coordinates_dict = coordinates_str.split('=')[1].split(']')[0] + ']'
            print(coordinates_dict)
            break

[37.680189359, 55.856497466]